import { Link } from "react-router-dom";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const LAST_UPDATED = "8 May 2026";

const sections = [
  {
    title: "Interpretation and Definitions",
    subsections: [
      {
        heading: "Interpretation",
        body: "The words of which the initial letter is capitalised have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in the plural.",
      },
      {
        heading: "Definitions",
        body: null,
        list: [
          { term: "Account", def: "means a unique account created for You to access our Service or parts of our Service." },
          { term: "Company", def: '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Keego Properties, Business Bay, Dubai, UAE.' },
          { term: "Cookies", def: "are small files placed on Your computer, mobile device or any other device by a website, containing details of Your browsing history on that website among its many uses." },
          { term: "Country", def: "refers to: United Arab Emirates." },
          { term: "Device", def: "means any device that can access the Service such as a computer, a cellphone or a digital tablet." },
          { term: "Personal Data", def: "is any information that relates to an identified or identifiable individual." },
          { term: "Service", def: "refers to the Website." },
          { term: "Service Provider", def: "means any natural or legal person who processes data on behalf of the Company to facilitate or analyse the Service." },
          { term: "Usage Data", def: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself." },
          { term: "Website", def: "refers to Keego Properties, accessible from keegoproperties.com." },
          { term: "You", def: "means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service." },
        ],
      },
    ],
  },
  {
    title: "Collecting and Using Your Personal Data",
    subsections: [
      {
        heading: "Types of Data Collected",
        body: "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include, but is not limited to: Email address, First name and last name, Phone number, and Usage Data.",
      },
      {
        heading: "Usage Data",
        body: "Usage Data is collected automatically when using the Service. It may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
      },
      {
        heading: "Tracking Technologies and Cookies",
        body: "We use Cookies and similar tracking technologies to track activity on Our Service and store certain information. We use both Session and Persistent Cookies for the purposes of providing and improving the Service. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.",
      },
    ],
  },
  {
    title: "Use of Your Personal Data",
    subsections: [
      {
        heading: null,
        body: "The Company may use Personal Data for the following purposes:",
        list: [
          { term: "To provide and maintain our Service", def: "including to monitor the usage of our Service." },
          { term: "To manage Your Account", def: "to manage Your registration as a user of the Service." },
          { term: "To contact You", def: "by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates, informative communications, or security updates." },
          { term: "To provide You with news and offers", def: "about goods, services and events similar to those you have already purchased or enquired about, unless You have opted not to receive such information." },
          { term: "To manage Your requests", def: "to attend and manage Your requests to Us." },
          { term: "For business transfers", def: "We may use Your information to evaluate or conduct a merger, divestiture, restructuring, or other transfer of some or all of Our assets." },
          { term: "For other purposes", def: "such as data analysis, identifying usage trends, and evaluating the effectiveness of our promotional campaigns." },
        ],
      },
    ],
  },
  {
    title: "Retention of Your Personal Data",
    subsections: [
      {
        heading: null,
        body: "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service.",
      },
    ],
  },
  {
    title: "Transfer of Your Personal Data",
    subsections: [
      {
        heading: null,
        body: "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.",
      },
    ],
  },
  {
    title: "Disclosure of Your Personal Data",
    subsections: [
      {
        heading: "Business Transactions",
        body: "If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.",
      },
      {
        heading: "Law Enforcement",
        body: "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).",
      },
      {
        heading: "Other Legal Requirements",
        body: "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to: comply with a legal obligation; protect and defend the rights or property of the Company; prevent or investigate possible wrongdoing in connection with the Service; protect the personal safety of Users of the Service or the public; protect against legal liability.",
      },
    ],
  },
  {
    title: "Security of Your Personal Data",
    subsections: [
      {
        heading: null,
        body: "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
      },
    ],
  },
  {
    title: "Children's Privacy",
    subsections: [
      {
        heading: null,
        body: "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please Contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.",
      },
    ],
  },
  {
    title: "Links to Other Websites",
    subsections: [
      {
        heading: null,
        body: "Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.",
      },
    ],
  },
  {
    title: "Changes to this Privacy Policy",
    subsections: [
      {
        heading: null,
        body: "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service prior to the change becoming effective and update the \"Last updated\" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes.",
      },
    ],
  },
  {
    title: "Contact Us",
    subsections: [
      {
        heading: null,
        body: "If you have any questions about this Privacy Policy, You can contact us:",
        list: [
          { term: "By email", def: "info@keegoproperties.com" },
          { term: "By phone", def: "+971 54 391 2231" },
          { term: "By address", def: "Business Bay, Dubai, UAE" },
        ],
      },
    ],
  },
];

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-[#F8F6F1]">
      <Navbar />

      {/* Hero */}
      <section className="bg-navy-dark pt-40 pb-16">
        <div className="container mx-auto px-4">
          <p className="text-xs font-semibold uppercase tracking-widest text-gold mb-3">Legal</p>
          <h1 className="font-serif text-4xl md:text-5xl font-bold text-white mb-4">Privacy Policy</h1>
          <p className="text-white/60 text-sm">Last updated: {LAST_UPDATED}</p>
          <p className="mt-5 max-w-2xl text-white/70 text-sm leading-relaxed">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.
            We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-14">
        <div className="container mx-auto px-4">
          <div className="grid lg:grid-cols-[240px_1fr] gap-10">

            {/* Sticky ToC */}
            <nav className="hidden lg:block">
              <div className="sticky top-28 rounded-2xl border border-border bg-white p-5 shadow-sm">
                <p className="text-xs font-semibold uppercase tracking-widest text-gold mb-4">Contents</p>
                <ol className="space-y-2">
                  {sections.map((s, i) => (
                    <li key={s.title}>
                      <a
                        href={`#section-${i}`}
                        className="text-xs text-muted-foreground leading-snug hover:text-foreground transition-colors"
                      >
                        {i + 1}. {s.title}
                      </a>
                    </li>
                  ))}
                </ol>
              </div>
            </nav>

            {/* Body */}
            <div className="space-y-10">
              {sections.map((section, i) => (
                <div
                  key={section.title}
                  id={`section-${i}`}
                  className="rounded-3xl border border-border bg-white p-8 shadow-sm scroll-mt-32"
                >
                  <h2 className="font-serif text-2xl font-bold text-foreground mb-5 pb-3 border-b border-border">
                    {i + 1}. {section.title}
                  </h2>
                  {section.subsections.map((sub, j) => (
                    <div key={j} className="mb-5 last:mb-0">
                      {sub.heading && (
                        <h3 className="font-semibold text-foreground mb-2">{sub.heading}</h3>
                      )}
                      {sub.body && (
                        <p className="text-sm leading-relaxed text-muted-foreground mb-3">{sub.body}</p>
                      )}
                      {sub.list && (
                        <ul className="space-y-2">
                          {sub.list.map((item) => (
                            <li key={item.term} className="flex gap-2 text-sm text-muted-foreground">
                              <span className="shrink-0 font-medium text-foreground">{item.term}:</span>
                              <span className="leading-relaxed">{item.def}</span>
                            </li>
                          ))}
                        </ul>
                      )}
                    </div>
                  ))}
                </div>
              ))}

              {/* CTA */}
              <div className="rounded-3xl bg-navy-dark p-8 text-center">
                <p className="text-xs font-semibold uppercase tracking-widest text-gold mb-2">Need Assistance?</p>
                <h3 className="font-serif text-2xl font-bold text-white mb-3">We're here to help</h3>
                <p className="text-white/65 text-sm mb-6">If you have any questions or concerns about this policy, our team is ready to assist.</p>
                <Link
                  to="/contact"
                  className="inline-flex items-center gap-2 rounded-full bg-gold px-7 py-2.5 text-sm font-semibold text-navy-dark hover:bg-gold/90 transition-colors"
                >
                  Contact Us
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
